In [42]:
import numpy as np 
import pandas as pd
import seaborn as sns 
import tensorflow as tf
import matplotlib.pyplot as plt

In [43]:
df=pd.read_csv('D:/vs_code_dl/files/diabetes.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [44]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [45]:
df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [46]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [47]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [48]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [49]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [50]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[0.05882353, 0.47738693, 0.49180328, ..., 0.3561848 , 0.07771136,
        0.01666667],
       [0.29411765, 0.52763819, 0.59016393, ..., 0.54992548, 0.03458582,
        0.11666667],
       [0.        , 0.67839196, 0.55737705, ..., 0.63040238, 0.12254483,
        0.05      ],
       ...,
       [0.58823529, 0.50753769, 0.70491803, ..., 0.67958271, 0.45175064,
        0.28333333],
       [0.        , 0.70854271, 0.        , ..., 0.6318927 , 0.05422716,
        0.13333333],
       [0.        , 0.6281407 , 0.78688525, ..., 0.33532042, 0.07856533,
        0.        ]], shape=(537, 8))

In [51]:
#model creation
from keras.models import Sequential
from keras.layers import Dense

In [52]:
ann=Sequential() #intialization
#input layer
ann.add(Dense(units=4,activation='relu'))
#hidden layer
ann.add(Dense(units=10,activation='relu'))
#hidden layer
ann.add(Dense(units=6,activation='relu'))

#op layer
ann.add(Dense(units=1,activation='sigmoid'))

In [53]:
#compile
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [54]:
ann.fit(x_train,y_train,epochs=100,batch_size=20)

Epoch 1/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.3687 - loss: 0.7025
Epoch 2/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6201 - loss: 0.6880
Epoch 3/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6518 - loss: 0.6792
Epoch 4/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6740
Epoch 5/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6692
Epoch 6/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6649
Epoch 7/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6604
Epoch 8/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6568
Epoch 9/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6537
Epoch 10/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6499 - loss: 0.6516
Epoch 11/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6499 - loss: 0.6499
Epoch 12/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6481
Epoch 13/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6499 - loss: 0.6466
Epoch 14/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6453
Epoch 15/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6499 - loss: 0.6437
Epoch 16/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6499 - loss: 0.6419
Epoch 17/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6499 - loss: 0.6404
Epoch 18/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6387
Epoch 19/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6499 - loss: 0.6369
Epoch 20/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6353
Epoch 21/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6328
Epoch 22/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6499 - loss: 0.6304
Epoch 23/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6499 - loss: 0.6281
Epoch 24/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6499 - loss: 0.6253
Epoch 25/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6499 - loss: 0.6235
Epoch 26/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6499 - loss: 0.6198
Epoch 27/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6480 - loss: 0.6168
Epoch 28/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6555 - loss: 0.6141
Epoch 29/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6536 - loss: 0.6102
Epoch 30/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6760 - loss: 0.6073
Epoch 31/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6667 - loss: 0.6042
Epoch 32/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6816 - loss: 0.6011
Epoch 33/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6946 - loss: 0.5976
Epoch 34/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6983 - loss: 0.5941
Epoch 35/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6909 - loss: 0.5919
Epoch 36/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6946 - loss: 0.5870
Epoch 37/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7058 - loss: 0.5847
Epoch 38/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6965 - loss: 0.5808
Epoch 39/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6946 - loss: 0.5779
Epoch 40/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7114 - loss: 0.5739
Epoch 41/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7151 - loss: 0.5702
Epoch 42/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7132 - loss: 0.5672
Epoch 43/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7169 - loss: 0.5645
Epoch 44/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7132 - loss: 0.5615
Epoch 45/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7207 - loss: 0.5585
Epoch 46/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7207 - loss: 0.5549
Epoch 47/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7225 - loss: 0.5527
Epoch 48/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7169 - loss: 0.5506
Epoch 49/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7244 - loss: 0.5473
Epoch 50/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7188 - loss: 0.5461
Epoch 51/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7188 - loss: 0.5424
Epoch 52/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7188 - loss: 0.5397
Epoch 53/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7318 - loss: 0.5363
Epoch 54/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7318 - loss: 0.5334
Epoch 55/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7263 - loss: 0.5333
Epoch 56/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7337 - loss: 0.5302
Epoch 57/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7300 - loss: 0.5280
Epoch 58/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7337 - loss: 0.5266
Epoch 59/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7374 - loss: 0.5228
Epoch 60/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7356 - loss: 0.5206
Epoch 61/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7374 - loss: 0.5187
Epoch 62/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7412 - loss: 0.5189
Epoch 63/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7486 - loss: 0.5160
Epoch 64/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7393 - loss: 0.5123
Epoch 65/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7430 - loss: 0.5139
Epoch 66/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7412 - loss: 0.5119
Epoch 67/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7430 - loss: 0.5075
Epoch 68/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7598 - loss: 0.5057
Epoch 69/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7505 - loss: 0.5034
Epoch 70/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7598 - loss: 0.5022
Epoch 71/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7579 - loss: 0.4996
Epoch 72/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7598 - loss: 0.4983
Epoch 73/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7523 - loss: 0.4976
Epoch 74/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7598 - loss: 0.4953
Epoch 75/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7616 - loss: 0.4939
Epoch 76/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7598 - loss: 0.4923
Epoch 77/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7672 - loss: 0.4912
Epoch 78/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7635 - loss: 0.4892
Epoch 79/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7709 - loss: 0.4873
Epoch 80/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7561 - loss: 0.4879
Epoch 81/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7728 - loss: 0.4851
Epoch 82/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7728 - loss: 0.4840
Epoch 83/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7691 - loss: 0.4827
Epoch 84/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7728 - loss: 0.4802
Epoch 85/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7709 - loss: 0.4804
Epoch 86/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7579 - loss: 0.4806
Epoch 87/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7709 - loss: 0.4811
Epoch 88/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7747 - loss: 0.4787
Epoch 89/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7654 - loss: 0.4770
Epoch 90/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7728 - loss: 0.4735
Epoch 91/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7728 - loss: 0.4720
Epoch 92/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7728 - loss: 0.4764
Epoch 93/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7709 - loss: 0.4718
Epoch 94/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7728 - loss: 0.4694
Epoch 95/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7728 - loss: 0.4694
Epoch 96/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7747 - loss: 0.4698
Epoch 97/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7728 - loss: 0.4677
Epoch 98/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7672 - loss: 0.4656
Epoch 99/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7691 - loss: 0.4659
Epoch 100/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7579 - loss: 0.4661

In [55]:
ann.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 10)             │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 6)              │            66 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │             7 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 479 (1.88 KB)

 Trainable params: 159 (636.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 320 (1.25 KB)

In [56]:
ann.evaluate(x_test,y_test)

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7100 - loss: 0.5361

[0.5361334681510925, 0.709956705570221]

In [57]:
x_train.shape

(537, 8)

In [58]:
y_pred=ann.predict(x_test)
y_pred

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

array([[0.5994513 ],
       [0.08732904],
       [0.07446897],
       [0.395135  ],
       [0.7304278 ],
       [0.7871579 ],
       [0.04281316],
       [0.22737642],
       [0.6349019 ],
       [0.39064857],
       [0.3814539 ],
       [0.7572762 ],
       [0.33688846],
       [0.7305645 ],
       [0.11242682],
       [0.5191852 ],
       [0.1317941 ],
       [0.07897872],
       [0.2827849 ],
       [0.38504395],
       [0.5711275 ],
       [0.12910362],
       [0.62375844],
       [0.07355217],
       [0.6044345 ],
       [0.8192977 ],
       [0.11847597],
       [0.0636142 ],
       [0.12284227],
       [0.36094707],
       [0.7434968 ],
       [0.38593695],
       [0.66363287],
       [0.49097866],
       [0.85398036],
       [0.7416093 ],
       [0.7851386 ],
       [0.5616275 ],
       [0.39424852],
       [0.51940656],
       [0.10502678],
       [0.2112273 ],
       [0.65171456],
       [0.4741229 ],
       [0.05313681],
       [0.583851  ],
       [0.8244033 ],
       [0.17755081],
       [0.342578  ],
       [0.8663285 ],
       [0.04143048],
       [0.8353853 ],
       [0.84747654],
       [0.2174468 ],
       [0.09464089],
       [0.04687826],
       [0.31163016],
       [0.06154254],
       [0.36400425],
       [0.7318481 ],
       [0.7850725 ],
       [0.26505208],
       [0.63777137],
       [0.67994046],
       [0.06888565],
       [0.34542453],
       [0.06555294],
       [0.65776825],
       [0.10613925],
       [0.74160314],
       [0.8194709 ],
       [0.15525891],
       [0.37082675],
       [0.09297815],
       [0.12956446],
       [0.8527323 ],
       [0.60559714],
       [0.5346146 ],
       [0.14112179],
       [0.21636845],
       [0.6767783 ],
       [0.12873049],
       [0.15447532],
       [0.2629103 ],
       [0.26473084],
       [0.80668277],
       [0.7822354 ],
       [0.49374008],
       [0.16597569],
       [0.08325137],
       [0.08786611],
       [0.20329736],
       [0.05726407],
       [0.2704696 ],
       [0.41888142],
       [0.5219114 ],
       [0.6031111 ],
       [0.14491145],
       [0.6475351 ],
       [0.28475803],
       [0.83292943],
       [0.05755761],
       [0.784611  ],
       [0.43522593],
       [0.67836344],
       [0.19937292],
       [0.28890958],
       [0.7845891 ],
       [0.30711356],
       [0.79062617],
       [0.08771046],
       [0.2147317 ],
       [0.08544053],
       [0.78401953],
       [0.20208627],
       [0.20279421],
       [0.5595202 ],
       [0.26523563],
       [0.08196563],
       [0.37089384],
       [0.05456053],
       [0.25187021],
       [0.19462644],
       [0.2411811 ],
       [0.1657747 ],
       [0.7044192 ],
       [0.0896236 ],
       [0.7309213 ],
       [0.38090116],
       [0.7870647 ],
       [0.69692934],
       [0.8320428 ],
       [0.16857268],
       [0.5975006 ],
       [0.7686024 ],
       [0.16480386],
       [0.09550682],
       [0.813885  ],
       [0.7845712 ],
       [0.0394756 ],
       [0.09596477],
       [0.05842792],
       [0.21695684],
       [0.3168112 ],
       [0.12007283],
       [0.44372755],
       [0.40482616],
       [0.04220117],
       [0.47800243],
       [0.75715494],
       [0.25139776],
       [0.56992453],
       [0.3189504 ],
       [0.44439766],
       [0.06276292],
       [0.74272937],
       [0.28482142],
       [0.14206949],
       [0.8284111 ],
       [0.14181586],
       [0.33182874],
       [0.7228722 ],
       [0.16904297],
       [0.04263395],
       [0.11410829],
       [0.6550876 ],
       [0.04737997],
       [0.22085524],
       [0.73807836],
       [0.70404655],
       [0.68558156],
       [0.3143668 ],
       [0.4113952 ],
       [0.515326  ],
       [0.7149061 ],
       [0.17610769],
       [0.28355893],
       [0.61746144],
       [0.5958413 ],
       [0.47695157],
       [0.53508466],
       [0.4108962 ],
       [0.5347408 ],
       [0.4951561 ],
       [0.7616774 ],
       [0.10116636],
       [0.06410734],
       [0.1784963 ],
       [0.36593884],
       [0.55469966],
       [0.08369596],
       [0.10398565],
       [0.26833707],
       [0.15392534],
       [0.34205493],
       [0.09521312],
       [0.03795041],
       [0.06943497],
       [0.28320098],
       [0.5940088 ],
       [0.22345775],
       [0.09574731],
       [0.7341524 ],
       [0.59714615],
       [0.745849  ],
       [0.12025596],
       [0.10366665],
       [0.21207829],
       [0.8371963 ],
       [0.7709559 ],
       [0.27861062],
       [0.15326235],
       [0.1216304 ],
       [0.2814349 ],
       [0.81689256],
       [0.10179966],
       [0.55838144],
       [0.5160849 ],
       [0.30119815],
       [0.7471652 ],
       [0.34116971],
       [0.33848652],
       [0.13979164],
       [0.15851256],
       [0.12514995],
       [0.3451533 ],
       [0.22817238],
       [0.3475359 ],
       [0.30013257],
       [0.29262963],
       [0.16991463]], dtype=float32)

In [59]:
y_pred=ann.predict(scaler.transform([[5,130,80,32,0,31.2,0.672,45]]))
y_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

array([[0.7600889]], dtype=float32)

In [60]:
if y_pred>0.5:
    print("Diabetic Patient")
else:
    print("Not a Diabetic Patient")

Diabetic Patient